// Generated by CoffeeScript 1.6.2
var checkStateChange, init, xmlDoc;

xmlDoc = null;

init = function() {
  xmlDoc = new XMLHttpRequest();
  xmlDoc.onreadystatechange = checkStateChange;
  xmlDoc.open('get', '../txt/introduction.md', true);
  return xmlDoc.send(null);
};

checkStateChange = function() {
  var txt;

  if (xmlDoc.readyState === 4 && (xmlDoc.status === 0 || xmlDoc.status === 200)) {
    txt = xmlDoc.responseText;
    document.getElementById('md').innerHTML = markdown.toHTML(txt);
    return console.log(document.getElementsByTagName('body')[0].innerHTML);
  }
};

window.onload = init;
